### ISSUE TITLE
Remove electric-marble-components import from electric core

### ISSUE THREAD

**Issue by matuzalemsteles** [electricjs/electric#128]
Hey guys, for the Electric API generation we have `api-component.tpl` which imports the soy `ElectricAPIEntities.soy.js` gross marble, that we prevent from generalizing the API to another set of components like `electric-clay-components`.

```
import 'electric-marble-components/lib/ElectricAPIEntities.soy.js';
```
[api-component.tpl L10](https://github.com/electricjs/electric/blob/6f9c6e3e7632412212d7cd18e5b22d016c7b9f01/packages/electric/lib/templates/api-component.tpl#L10)

#### Proposal 1

We can remove the import and add the **ElectricAPIEntities** in our project, for example in `src/partials/ElectricAPIEntities.soy` and let the Electric import it, I do not know if it is the most viable way or if it will have consequences in the future.

#### Proposal 2

Create an API to tell which set of components you want to use. We have the `metalComponents` API but we have a problem that your API is an array and we will not know where the `ElectricAPIEntities` file is. We can create a specific in `apiConfig` for this but maybe it can get confusing.

I like the first option since `api-soyweb.tpl` calls `ElectricApi.render` and it calls `ElectricAPIEntities`, have more sense, and that **ElectricApi** is in our project and we can customize according to the characteristics of the project.

What do you think? Do you have any suggestions about this?

cc @jbalsas @zenorocha

**Comment by jbalsas** [comment]
Hey @matuzalemsteles, as we discussed offline, I would follow the pattern in that file and just make the import configurable with something like:

```
import '<%= apiEntitiesPath %>soy.js';
```

That way, setting the default to `electric-marble-components/lib/ElectricAPIEntities` we avoid a breaking change and can move forward.

**Comment by matuzalemsteles** [comment]
Hey @jbalsas I will continue with this so that we do not have a breaking change, but I think we should put in TODO to remove its default value in the future.

**Comment by jbalsas** [comment]
Yes, sounds good to me. Could you please open an issue with that? We can schedule it for the next major release.
