### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by silverhook** [electricjs/electric#156]
Electric seems to be under `BSD-3-Clause` license – both on its website and its `LICENSE` file.

But in the following 6 `package.json` files it states `ISC` as the license:

- packages/electric-cli/package.json
- packages/electric-base-components/package.json
- packages/electric-clay-components/package.json
- packages/electric-marble-components/package.json
- packages/generator-electric/package.json
- packages/electric/package.json

I would suggest to change the `"license": "ISC",` line in those files to `"license": "BSD-3-Clause",`, so the information will be be coherent throughout.

If, though, the (sub)packages are indeed intended to be licensed differently as the main repository, do let me know, and we’ll work on clarifying that in the README. :)

Either way, I can provide a PR, if needed.

**Comment by jbalsas** [comment]
Hey @silverhook, we're discontinuing Electric in favor of industry software like [Gatsby](https://www.gatsbyjs.org/), so we're not really planning to release any new versions of those packages. 

Do you think it's still important to update those? If affirmative... I would greatly appreciate a PR 🙏

**Comment by silverhook** [comment]
Even if we abandon it, it would make sense to leave it with a clear licensing situation. I’ll open a PR. Feel free to assign this to me.

Should I work directly on master or devel?

**Comment by jbalsas** [comment]
Cool, thanks!

Send directly to `master`, that should do it! ☺️

**Comment by silverhook** [comment]
@jbalsas, finally got around to do it – please find the PR above :)

In the PR I also explain how I got to this result.
