### ISSUE TITLE
Missing metal-soy-bundle functions during soyweb rendering

### ISSUE THREAD

**Issue by eduardolundgren** [electricjs/electric#26]
Creating a `pages/foo.soy` using https://github.com/metal/metal-tabs/releases/tag/v2.2.0:

```
{namespace pageTabs}

/**
 */
{template .render}
	{call main.render data="all"}
		{param content kind="html"}
			Hello!
			{call Tabs.render}
				{param tab: 0 /}
				{param tabs: [
						['label': 'Tab1'],
						['label': 'Tab2'],
				] /}
			{/call}
		{/param}
	{/call}
{/template}
```

It gives an error when compiling soyweb:

```
TypeError: goog.asserts.assertNumber is not a function
    at Object.Tabs.render (/tmp/soynode/node_modules/metal-tabs/src/Tabs.soy.js:25:26)
    at Object.pageTabs.render (/tmp/soynode/temp/soyweb/pages/tabs.soy.js:19:174)
    at pageTabs.soyweb (/tmp/soynode/temp/soyweb/pages/tabs.soy.js:34:172)
    at SoyCompiler.render (/Users/eduardo/Projects/gocompras.us/node_modules/soynode/lib/SoyCompiler.js:102:47)
    at renderSoyWeb (/Users/eduardo/Projects/gocompras.us/node_modules/gulp-soynode/index.js:198:26)
    at /Users/eduardo/Projects/gocompras.us/node_modules/gulp-soynode/index.js:140:20
    at Array.forEach (native)
    at /Users/eduardo/Projects/gocompras.us/node_modules/gulp-soynode/index.js:125:15
    at Array.forEach (native)
    at EventEmitter.<anonymous> (/Users/eduardo/Projects/gocompras.us/node_modules/gulp-soynode/index.js:118:11)
```

This error can be printed if manually `console.log(err)` on https://github.com/eduardolundgren/gulp-soynode/blob/master/index.js#L141.

The reason is because using `gulp-soynode` we don't include https://github.com/metal/metal-soy-bundle functions. We can try to include those functions in the generated file from soynode or use https://github.com/metal/metal-tools-soy that @mairatma created.

@mairatma Do you have any recommendation here? Thank you.

**Comment by mairatma** [comment]
It would be weird to add from gulp-soynode I think, since people may want to add these functions in different ways, and metal-tools-soy is specific to how we do it for metal projects.

**Comment by eduardolundgren** [comment]
@mairatma `gulp-soynode` supports `{template .soyweb}` and this feature [render the content from the compiled JavaScript](https://github.com/eduardolundgren/gulp-soynode/blob/master/index.js#L194). The compiled JavaScript may require `goog.asserts` and other runtime functions, therefore it will fail without those functions loaded.

The issue is in `gulp-soynode` that will fail when the output require those dependencies. What would be the best approach here?

**Comment by mairatma** [comment]
Ah got it, only during runtime right? Not sure what would be the best way today. Ideally google would provide this bundle for us, but since they don't, using metal-soy-bundle may be the only way to go.

**Comment by eduardolundgren** [comment]
@mairatma yep, during runtime.

If https://github.com/metal/metal-soy-bundle is loaded in the `gulp-soynode` VM context this might do the job. Or, maybe checking if the new https://github.com/medium/soynode version already includes it since they have new options such as `shouldProvideRequireJsFunctions`.

@Robert-Frampton could you investigate? Thank you.
