### ISSUE TITLE
Soy output defaults to /tmp

### ISSUE THREAD

**Issue by victorvalle** [electricjs/electric#38]
When invoking `gulp-soynode` in https://github.com/wedeploy/electric/blob/master/lib/tasks/soyweb.js#L57-L81, we're not passing the `outputDir` option.

This [makes it default to `/tmp/soynode`](https://github.com/eduardolundgren/gulp-soynode/blob/master/index.js#L31), which may cause issues depending on the permission system of the user. 

Looks like the similar issue may be affecting our usage of `metal-tools-soy` as well.

Is there a specific reason for that? Shouldn't we make sure the output dir stays contained within the project?

**Comment by victorvalle** [comment]
This also happens for [metal-tools-soy](https://github.com/metal/metal-tools-soy/blob/master/lib/pipelines/compileSoy.js#L202) which isn't even configurable, so this is definitely a permissions error, but it probably could be prevented with more sensible defaults...

**Comment by Robert-Frampton** [comment]
Hey @victorvalle 

I sent in a pr for making it configurable in metal-tools-soy. Once that's published I can go into electric and change outputDir for both gulp-soynode/metal-tools-soy.

**Comment by Robert-Frampton** [comment]
1b23ff9de31a6e51642e71ebd19526251ec197e8
