### ISSUE TITLE
Front Matter not calling inside code blocks

### ISSUE THREAD

**Issue by jonnilundy** [electricjs/electric#42]
I am trying to create a page variable in the front matter of a blog and pass it inside of a code block, but it is not rendering. The same variable is working outside of the code block as a normal paragraph element. 

My guess is that it has to do with the brackets being rendered differently inside of a `<pre>` element.

**Here is my front matter:**
![image](https://cloud.githubusercontent.com/assets/23219848/24564560/1d9362a0-1607-11e7-8b77-d0f4c0ff2498.png)

**Here is the code:**
![image](https://cloud.githubusercontent.com/assets/23219848/24564617/51db0752-1607-11e7-8edf-18305a163394.png)

**Here is what it is rendering:**
![image](https://cloud.githubusercontent.com/assets/23219848/24564524/05b22a86-1607-11e7-8b5f-b2de6a3a9e38.png)

**Comment by Robert-Frampton** [comment]
Yeah, by default we wrap everything in ` ``` ` with a `{literal}` block to make it easier to write code examples that have brackets, which means you can't pass variables into it.

If you really need to pass variables into a code example, you'll have to call the `ElectricCode` component directly.

```
{call ElectricCode.render}
	{param code kind="text"}
		{$page.directory}
	{/param}
	{param mode: 'lang' /}
{/call}
```

Mind you that when you don't use a `{literal}` block and you need to write a bracket, you'll have to escape them with `{lb}` and `{rb}`.

```
{call ElectricCode.render}
	{param code kind="text"}
		if (true) {lb}
			console.log({$page.directory});
		{rb}
	{/param}
	{param mode: 'javascript' /}
{/call}
```

**Comment by jonnilundy** [comment]
I see. Thanks for explaining, @Robert-Frampton!
