### ISSUE TITLE
Normalize code style

### ISSUE THREAD

**Issue by julien** [electricjs/electric#5]
Hi,

This is more a question than an issue.

In the project we have a `.jshintrc` file that specifies the `indent` option (set to `2`), as you can see [here](http://jshint.com/docs/options/#indent) this option is deprecated and on the other side it seems that the main source files use the tab character (with a width of 4 chars) so I was wondering: 

Should we use the [jscs](https://github.com/jscs-dev/node-jscs) tool?
Should we use another linter ([eslint](http://eslint.org))?
Should we add an `.editorconfig` file?

Thanks

**Comment by pragmaticivan** [comment]
I submited a PR for google js styleguide, since this project is on wedeploy organization, most of the projects are using that as default: 

```
Please follow the [Google javascript style guide](http://google.github.io/styleguide/jsguide.html).
```
https://github.com/google/eslint-config-google

**Comment by Robert-Frampton** [comment]
It looks like we're not linting with just these rules https://github.com/wedeploy/api-js/blob/master/.eslintrc.json#L18-L24.

It would be nice to abstract this config so we can easily make sure all projects are consistent.

**Comment by pragmaticivan** [comment]
@Robert-Frampton those rules are applied till we get on the expected state without changing a lot of code.

Probably the goal is to use eslint like: https://github.com/wedeploy/magnet/blob/master/.eslintrc

**Comment by Robert-Frampton** [comment]
Since we are using [prettier](https://www.npmjs.com/package/prettier) in our other projects, I've implemented it here as well.
