### ISSUE TITLE
Hide .publish and temp folders

### ISSUE THREAD

**Issue by zenorocha** [electricjs/electric#50]
A typical Electric project looks like this:

<img width="200" alt="screen shot 2017-05-17 at 2 00 51 pm" src="https://cloud.githubusercontent.com/assets/398893/26175943/4b20a7d8-3b09-11e7-88d0-7e42594a7b00.png">

`.publish` and `temp` are useless to the developer, so what do you think of putting them inside `node_modules`?

**Comment by Robert-Frampton** [comment]
After discussing this with @zenorocha, `temp` has been renamed to `.temp`, and both `.temp` and `.publish` are cleaned after the task has finished.
