### ISSUE TITLE
Issue with vendors in tutorials

### ISSUE THREAD

**Issue by jonnilundy** [electricjs/electric#51]
On the current version of the CLI, there seems to be a bug that prevents some of the vendors from working on the tutorials. Based on [wedeploy.com](http://wedeploy.com/tutorials/), here are some of the symptoms.

- **Moment**: The time-remaining element is gone and there is a console error saying that the `moment` variable is not defined.
- **Copy to Clipboard**: Copy to clipboard buttons are not working. No console error.
- **CodeMirror**: Code blocks are [not loading on first load](https://cloud.githubusercontent.com/assets/23219848/26429025/8877520e-4099-11e7-8fc6-6fe4eab1d6e1.png). The user must refresh the page again for them to load.

**Comment by jbalsas** [comment]
Hey @jonnilundy, I think that is an issue with a component inside the `wedeploy.com` project. I've sent https://github.com/wedeploy/wedeploy.com/pull/187. Could you please verify that fixes this issue?

Thanks!

**Comment by jonnilundy** [comment]
Just verified! Works great. Thanks @jbalsas!
