### ISSUE TITLE
Suggestion Hidden pages

### ISSUE THREAD

**Issue by victorvalle** [electricjs/electric#64]
It would be nice to have an attribute hide in the page properties to hide a page from the navigation. In this way when a page is in work in progress I don't need to care that much when I deploy.

**Comment by zenorocha** [comment]
Try using `hidden: true` on the front-matter area. This needs to be documented.

**Comment by Robert-Frampton** [comment]
@victorvalle 

Did that work for you?

**Comment by victorvalle** [comment]
Yes, sorry.
