### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by julien** [electricjs/electric#8]
Hi,

I have a fork of this repository that I cloned on January 16 2017 and was looking at the code to study the code, when I tried to run the tests this morning I saw three of them were failing.

So to double check I cloned the repository again in a new location, with the following commands:

```shell
cd ~
mkdir -p tmp
cd $_
npm it
```

It seems that the tests are failing, I'm working on it and will sent a PR soon.

Thanks.

**Comment by Robert-Frampton** [comment]
Hey @julien, we removed some of the old tests and are in the process of writing new ones using jest snapshots, so I'm going to close this for now.

**Comment by julien** [comment]
Hey @Robert-Frampton, makes sense. Thanks for the update and let me know if I can help.
