### ISSUE TITLE
Make a request on build time and expose result as metadata

### ISSUE THREAD

**Issue by zenorocha** [electricjs/electric#80]
Today we have a page that loads a certain API in order to be built: https://community.liferay.com/user-groups/

It would be nice if we could make a request during the build process and expose the result of that request as a metadata. Something similar to this: https://github.com/ahmadnassri/metalsmith-request

What do you think?

**Comment by Robert-Frampton** [comment]
Should be pretty simple, were you thinking configuring it per page via meta data? Or some top level config that goes into `electric.config.js`?

**Comment by zenorocha** [comment]
A top level config that goes into electric config should be fine.

**Comment by zenorocha** [comment]
Closing for now.
