### ISSUE TITLE
Anchors in URLs are ignored

### ISSUE THREAD

**Issue by juliocamarero** [electricjs/electric#87]
I have created a docs page with links to sections to other pages.

You can see the example here: https://pulpo.wedeploy.io/docs/datasources/

There is a link called "Pagination" with this url: https://pulpo.wedeploy.io/docs/general#pagination

If I copy and paste manually that URL to my browser, it will work fine, go to that page and move the focus to the pagination section.

However, when just clicking on the link, it will go just to https://pulpo.wedeploy.io/docs/general removing the anchor from the URL.

**Comment by Robert-Frampton** [comment]
Hey @juliocamarero 

I just tried it a couple of times on Chrome and it worked for me. What browser did you experience this with?

**Comment by juliocamarero** [comment]
You are right, I can't reproduce it anymore :O  I was using Chrome too. I will close the issue. Thank you!!
