### ISSUE TITLE
Error on project initialization

### ISSUE THREAD

**Issue by rafaelfe** [electricjs/electric#93]
I'm getting this error when I run `electric init`:
```
(node:1261) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: `email` required
(node:1261) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1261) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: `email` required
```

Versions:
Node 8.9.1
npm 5.5.1
Electric 2.2.0

System
ProductName:	Mac OS X
ProductVersion:	10.13.1
BuildVersion:	17B48

**Comment by rafaelfe** [comment]
**SOLVED**: this was happening after I updated to High Sierra. The update messed with git and the email info needed for project initialization could not be retrieved.

For anyone having the same  #problem with git after updating, run `xcode-select --install` to fix.

**Comment by zenorocha** [comment]
Cool! Thanks for sharing your fix @rafaelfe!

**Comment by evertonthepaula-objective** [comment]
I have same problem, then i try use de "generator-electric + electric-cli yo", but my terminal response is:

Error: `email` required
    at module.exports (/home/everton/.nvm/versions/node/v8.11.3/lib/node_modules/generator-electric/node_modules/github-username/index.js:6:9)

Versions:
NVM: 0.33.11
Node:8.11.3
NPM: 6.2.0

System:
Linux Ubuntu: 16.04

SOLVED:
I don't see the reference to directory "github-username" on error Message, im try search something wrong in my yeoman configuration. @matuzalemsteles  Thanks for help!

**Comment by matuzalemsteles** [comment]
hey @evertonthepaula-objective, Check that your machine is set up with your `username` and `email` in git.

https://git-scm.com/docs/git-config
