### ISSUE TITLE
Cannot use `{}` inside a Markdown

### ISSUE THREAD

**Issue by HenriqueLimas** [electricjs/electric#96]
I am trying to use `{}` inside a markdown but it says that `Found 'print' command with empty command text.` To resolve that I need to use `{lb}{rb}`, maybe is possible to compile braces for that characters.

**Comment by zenorocha** [comment]
Hey @HenriqueLimas!

One way to avoid that is maybe adding the `{literal}` tag. That will tell the compiler not to scape `{}`. If that doesn't work what you mentioned is a good replacement.

Thanks for reporting!
