### ISSUE TITLE
Electric site cannot be part of a lerna monorepo with hoisted deps

### ISSUE THREAD

**Issue by jbalsas** [electricjs/electric#98]
Currently, trying to have an electric site in a project with a lerna monorepo layout that uses hoist dependencies fails to build properly.

The reason is that WebPack's `CommonChunksPlugin` and `DedupePlugin` will fail to properly build the bundles due to [resolve.modules](https://webpack.js.org/configuration/resolve/#resolve-modules) defaulting to `node_modules`.

For such cases, it would be ideal if one could configure where the modules should be resolved from like:

```javascript
// electric.config.js
module.exports = {
    ...
    resolveModules: ['../../node_modules']
    ...
};
```

**Comment by Robert-Frampton** [comment]
Merged and published.
